In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

np.random.seed(1)

np.random.shuffle(a)
print(a)
np.random.shuffle(b)
print(b)

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

np.random.seed(1)
np.random.shuffle(a)
print(a)
np.random.seed(1)
np.random.shuffle(b)
print(b)


[ 3 10  7  5  1  4  2  8  9  6]
[10  6  4  1  9  5  3  2  7  8]
[ 3 10  7  5  1  4  2  8  9  6]
[ 3 10  7  5  1  4  2  8  9  6]
